services:
  eureka-server:
    container_name: eureka-server
    build:
      context: ./backend/eureka-server
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "8761:8761"
    networks:
      - microservice-network

  profile-service-db:
    container_name: profile-service-db
    image: postgres:15
    environment:
      POSTGRES_USER: ${PROFILE_DB_USER}
      POSTGRES_PASSWORD: ${PROFILE_DB_PASSWORD}
      POSTGRES_DB: ${PROFILE_DB}
    volumes:
      - profile_db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - microservice-network

  social-service-db:
    container_name: social-service-db
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SOCIAL_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${SOCIAL_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${SOCIAL_DB}
    volumes:
      - social_db_data:/data/db
    env_file:
      - .env
    ports:
      - "27017:27017"
    networks:
      - microservice-network

  profile-service:
    container_name: profile-service
    build:
      context: ./backend/profile-service
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${PROFILE_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${PROFILE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${PROFILE_DB_PASSWORD}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${AUTH0_ISSUER}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      eureka-server:
        condition: service_started
      profile-service-db:
        condition: service_started
    ports:
      - "8081:8080"
    networks:
      - microservice-network

  social-service:
    container_name: social-service
    build:
      context: ./backend/social-service
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${SOCIAL_DB_USER}:${SOCIAL_DB_PASSWORD}@${SOCIAL_DB_URL}/${SOCIAL_DB}?authSource=admin
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${AUTH0_ISSUER}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      eureka-server:
        condition: service_started
      social-service-db:
        condition: service_started
    ports:
      - "8082:8080"
    networks:
      - microservice-network

  gateway-service:
    container_name: gateway-service
    build:
      context: ./backend/gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${AUTH0_ISSUER}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      PROFILE_SERVICE_URL: ${GATEWAY_PROFILE_SERVICE_URL}
      SOCIAL_SERVICE_URL: ${GATEWAY_SOCIAL_SERVICE_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      eureka-server:
        condition: service_started
      profile-service:
        condition: service_started
      social-service:
        condition: service_started
    networks:
      - microservice-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      gateway-service:
        condition: service_started
    ports:
      - "80:80"
    networks:
      - microservice-network

volumes:
  profile_db_data:
  social_db_data:

networks:
  microservice-network:
    driver: bridge
