apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: gamemate-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: keyshr3kt/user-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: user-service-secrets
            - configMapRef:
                name: user-service-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: gamemate-backend
spec:
  selector:
    app: user-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
