apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor
  namespace: gamemate-infrastructure
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      prometheus: scrape
  namespaceSelector:
    matchNames:
      - gamemate-backend
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
