spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: profile-service
          uri: ${PROFILE_SERVICE_URL}
          predicates:
            - Path=/api/profile/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
