spring:
  application:
    name: social-service
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
