name: Build and Scan Docker Images

on:
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: user-service
            path: backend/user-service
            image: keyshr3kt/user-service:latest
          - name: eureka-server
            path: backend/eureka-server
            image: keyshr3kt/eureka-server:latest
          - name: social-service
            path: backend/social-service
            image: keyshr3kt/social-service:latest
          - name: gateway-service
            path: backend/gateway-service
            image: keyshr3kt/gateway-service:latest
          - name: gamemate-frontend
            path: frontend
            image: keyshr3kt/gamemate-frontend:latest

    env:
      IMAGE_TAG: latest
      TRIVY_VERSION: 0.51.1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t ${{ matrix.service.image }} "${{ matrix.service.path }}"

      - name: Install Trivy
        run: |
          mkdir -p trivy
          curl -sSL "https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz" | tar -xz -C trivy
          sudo mv trivy/trivy /usr/local/bin/trivy

      - name: Filesystem Security Scan
        run: trivy fs --exit-code 1 --scanners vuln --severity HIGH,CRITICAL --no-progress "${{ matrix.service.path }}"
        continue-on-error: false

      - name: Image Security Scan
        run: trivy image ${{ matrix.service.image }} --exit-code 1 --severity HIGH,CRITICAL --no-progress
        continue-on-error: true
