name: SonarQube Analysis for Backend Microservices

on:
  push:

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [social-service]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: backend/${{ matrix.service }}

      - name: Gradle Test and Jacoco Coverage
        working-directory: backend/${{ matrix.service }}
        run: ./gradlew clean test jacocoTestReport

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: backend/${{ matrix.service }}/build/reports/jacoco/test/

      - name: Run SonarQube Analysis
        working-directory: backend/${{ matrix.service }}
        env:
          SONAR_TOKEN_SOCIAL_SERVICE: ${{ secrets.SONAR_TOKEN_SOCIAL_SERVICE }}
        run: |
          SERVICE_KEY=$(echo "${{ matrix.service }}" | tr '-' '_' | tr '[:lower:]' '[:upper:]')
          SONAR_TOKEN_VAR="SONAR_TOKEN_${SERVICE_KEY}"
          SONAR_TOKEN="${!SONAR_TOKEN_VAR}"

          echo "Running SonarQube analysis for ${{ matrix.service }}"

          ./gradlew sonar \
            -Dsonar.projectKey=${{ matrix.service }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=$SONAR_TOKEN
        shell: bash
